<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUCr2kph\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUCr2kph/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUCr2kph.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUCr2kph\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUCr2kph\App_KernelDevDebugContainer([
    'container.build_hash' => 'UCr2kph',
    'container.build_id' => '2941f43b',
    'container.build_time' => 1653851638,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUCr2kph');
